version: '3.8'

services:
  bot:
    build: .
    container_name: teras
    env_file:
      - .env
    ports:
      - "25336:3001"
    restart: unless-stopped
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api:ro
    networks:
      - default

volumes:
  telegram-bot-api-data:
    name: telegram-bot-api-data
    external: true

networks:
  default:
    name: satuarah-network
    external: true
